# traefik.yml (static configuration)
log:
  level: DEBUG
api:
  dashboard: true
  insecure: true  # ⚠️ Only for testing; don't expose this in production
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  postgres-debug:
    address: ":5432"
providers:
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: johann@schwabe.dev
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
